-- ==============================================================================
-- Entornos Seguros - Script de Inicialización Automatizada de Base de Datos
-- Se ejecuta automáticamente al levantar el contenedor de Docker por primera vez
-- ==============================================================================

-- 1. Habilitar extensión geoespacial PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Crear los esquemas de cada microservicio
CREATE SCHEMA IF NOT EXISTS auth_user;
CREATE SCHEMA IF NOT EXISTS incident;
CREATE SCHEMA IF NOT EXISTS police_report;

-- ------------------------------------------------------------------------------
-- Esquema: auth_user
-- ------------------------------------------------------------------------------

-- Tabla de Roles
CREATE TABLE IF NOT EXISTS auth_user.rol (
    id_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL UNIQUE,
    descripcion varchar(150),
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

-- Catálogo de Roles iniciales
INSERT INTO auth_user.rol (id_rol, nombre, descripcion)
VALUES 
    (1, 'ADMINISTRADOR', 'Administrador del sistema con acceso global'),
    (2, 'POLICIA', 'Agente operativo policial para atención de incidentes'),
    (3, 'USUARIO', 'Ciudadano para reporte y seguimiento')
ON CONFLICT (id_rol) DO NOTHING;

-- Tabla de Usuarios
CREATE TABLE IF NOT EXISTS auth_user.usuario (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol bigint NOT NULL REFERENCES auth_user.rol(id_rol),
    cedula varchar(20) NOT NULL UNIQUE,
    nombres varchar(100) NOT NULL,
    apellidos varchar(100) NOT NULL,
    telefono varchar(20),
    correo varchar(120) NOT NULL UNIQUE,
    contrasena_hash varchar(255) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp NOT NULL DEFAULT NOW(),
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

-- Índices de búsqueda
CREATE INDEX IF NOT EXISTS idx_usuario_correo ON auth_user.usuario (correo);
CREATE INDEX IF NOT EXISTS idx_usuario_cedula ON auth_user.usuario (cedula);
CREATE INDEX IF NOT EXISTS idx_usuario_rol ON auth_user.usuario (id_rol);

-- Usuarios de prueba iniciales:
-- Admin:   Admin123!   -> $2a$10$ERYR06VQ//9uqmKEljUgD.0CrH7CW9zKkUCRKADZi8SQ14ZD2acPy
-- Policia: Policia123! -> $2a$10$wtISNvwAFE4iCSbdyR3gsuy6gqQ/eZek150zYBw8MYqtM2NG22.S2
INSERT INTO auth_user.usuario (id_rol, cedula, nombres, apellidos, telefono, correo, contrasena_hash, activo)
VALUES 
    (1, '80000001', 'Administrador', 'Principal', '3001112233', 'admin@entornosseguros.gov.co', '$2a$10$ERYR06VQ//9uqmKEljUgD.0CrH7CW9zKkUCRKADZi8SQ14ZD2acPy', true),
    (2, '80000002', 'Oficial', 'Patrullero', '3004445566', 'policia@entornosseguros.gov.co', '$2a$10$wtISNvwAFE4iCSbdyR3gsuy6gqQ/eZek150zYBw8MYqtM2NG22.S2', true)
ON CONFLICT (cedula) DO NOTHING;

-- Tabla de CAIs (con columna generada PostGIS)
CREATE TABLE IF NOT EXISTS auth_user.cai (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(50) NOT NULL UNIQUE,
    nombre varchar(120) NOT NULL,
    direccion varchar(150),
    telefono varchar(20),
    localidad varchar(80),
    latitud double precision NOT NULL,
    longitud double precision NOT NULL,
    geom geography(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitud, latitud), 4326)::geography) STORED,
    activo boolean NOT NULL DEFAULT true,
    source_object_id bigint,
    fecha_sincronizacion timestamp,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

-- Índices espaciales y de texto
CREATE INDEX IF NOT EXISTS idx_cai_geom ON auth_user.cai USING gist (geom);
CREATE INDEX IF NOT EXISTS idx_cai_localidad ON auth_user.cai (localidad);
CREATE INDEX IF NOT EXISTS idx_cai_activo ON auth_user.cai (activo);

-- Catálogo de CAIs muestra en Bogotá
INSERT INTO auth_user.cai (codigo, nombre, direccion, telefono, localidad, latitud, longitud)
VALUES 
    ('CAI-01', 'CAI Chapinero', 'Calle 63 con Carrera 13', '6013150001', 'Chapinero', 4.6486, -74.0632),
    ('CAI-02', 'CAI Parque de la 93', 'Carrera 11A con Calle 93A', '6013150002', 'Chapinero', 4.6766, -74.0519),
    ('CAI-03', 'CAI Usaquén', 'Carrera 7 con Calle 119', '6013150003', 'Usaquén', 4.6983, -74.0298),
    ('CAI-04', 'CAI Teusaquillo', 'Calle 34 con Carrera 19', '6013150004', 'Teusaquillo', 4.6272, -74.0725),
    ('CAI-05', 'CAI Ciudad Salitre', 'Avenida La Esperanza con Calle 50', '6013150005', 'Fontibón', 4.6542, -74.1086)
ON CONFLICT (codigo) DO NOTHING;
